# Generated by Django 5.0.1 on 2024-01-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reserved_books',
            field=models.ManyToManyField(blank=True, related_name='reserved_by', to='lmsapp.book'),
        ),
    ]
